"""Generates phase 0's test data into bench/out/fixtures. Deterministic: same bytes on every machine.

    uv run fixtures/generate.py            # everything that's missing
    uv run fixtures/generate.py --force    # regenerate everything

Writes:
  workspace/platform/        base Git repo with five nested, independent repos under services/
  diff/old.ts, diff/new.ts   5,000-line file before and after scattered changes (also the diff in
                             workspace/platform/services/catalog/src/inventory.ts)
  large/large.ts             5 MB source-like file
  dumps/normal.log           250 MB of line-oriented log output
  dumps/long.txt             250 MB of very long lines with few newlines
  dumps/emoji.txt            250 MB of combining-character runs mixed with emoji sequences
  dumps/load.log             50 MB log for the four-TUI load test
  manifest.json              paths, sizes and what a checker needs to verify each dump
"""

from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import subprocess
import sys
import time
import zlib
from pathlib import Path

VERSION = 1
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "bench" / "out" / "fixtures"
MB = 1024 * 1024

# --- source-like code ---------------------------------------------------------------------------

NOUNS = ["order", "invoice", "account", "session", "token", "product", "cart", "user", "price",
         "stock", "event", "queue", "batch", "report", "ledger", "refund", "coupon", "shipment"]
VERBS = ["load", "save", "find", "update", "validate", "compute", "merge", "parse", "render",
         "sync", "apply", "resolve", "fetch", "emit", "build", "check"]


def camel(*parts: str) -> str:
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def code_block(rng: random.Random, n: int) -> list[str]:
    """One TypeScript-looking function or class, about 15-60 lines."""
    noun, verb = rng.choice(NOUNS), rng.choice(VERBS)
    name = camel(verb, noun, str(n))
    if rng.random() < 0.3:
        cls = noun.capitalize() + f"Store{n}"
        lines = [f"export class {cls} {{", f"  private readonly items = new Map<string, {noun.capitalize()}>();", ""]
        for m in range(rng.randint(2, 5)):
            v = rng.choice(VERBS)
            lines += [
                f"  {camel(v, noun)}(id: string, limit = {rng.randint(1, 500)}): {noun.capitalize()} | undefined {{",
                f"    const item = this.items.get(id);",
                f"    if (!item || item.version < {rng.randint(1, 9)}) {{",
                f"      return undefined;",
                f"    }}",
                f"    // {v} the {noun} and keep at most `limit` entries",
                f"    return {{ ...item, updatedAt: Date.now(), limit }};",
                f"  }}",
                "",
            ]
        lines += ["}", ""]
        return lines
    lines = [
        f"/** {verb.capitalize()}s a {noun} and reports what changed. */",
        f"export async function {name}(input: {noun.capitalize()}Input, opts: Options = {{}}): Promise<Result> {{",
        f"  const started = performance.now();",
        f"  const retries = opts.retries ?? {rng.randint(0, 5)};",
    ]
    for i in range(rng.randint(4, 14)):
        a, b = rng.choice(NOUNS), rng.choice(VERBS)
        lines += rng.choice([
            [f"  const {a}{i} = await {camel(b, a)}(input.{a}Id, {{ timeout: {rng.randint(100, 9000)} }});"],
            [f"  if ({a}{i - 1 if i else 0}?.status === \"{rng.choice(['ok', 'stale', 'failed'])}\") {{",
             f"    log.debug(\"{b} {a}\", {{ id: input.id, attempt: {i} }});",
             f"  }}"],
            [f"  for (const item of input.{a}s ?? []) {{",
             f"    total += item.amount * {rng.randint(1, 99)};",
             f"  }}"],
            [f"  // TODO({rng.choice(['sena', 'agent', 'ops'])}): {b} {a} in bulk instead of one by one"],
        ])
    lines += [
        f"  return {{ ok: true, took: performance.now() - started, retries }};",
        "}",
        "",
    ]
    return lines


def code_lines(rng: random.Random, count: int) -> list[str]:
    lines = ["// Generated by bench/fixtures/generate.py. Not real code.",
             "import { log, performance } from \"./runtime\";", ""]
    n = 0
    while len(lines) < count:
        lines += code_block(rng, n)
        n += 1
    return lines[:count]


def scatter_changes(rng: random.Random, old: list[str]) -> list[str]:
    """Modifies, inserts and deletes lines at about 70 scattered places."""
    new: list[str] = []
    i = 0
    next_change = rng.randint(20, 120)
    while i < len(old):
        if i == next_change:
            kind = rng.choice(["modify", "modify", "insert", "delete", "replace"])
            if kind == "modify":
                line = old[i]
                for a, b in [("const ", "let "), ("await ", "await retry("), ("ok: true", "ok: !failed"),
                             ("debug", "info"), ("?? ", "|| ")]:
                    if a in line:
                        line = line.replace(a, b, 1)
                        break
                else:
                    line = line + " // changed"
                new.append(line)
                i += 1
            elif kind == "insert":
                indent = old[i][: len(old[i]) - len(old[i].lstrip())]
                for k in range(rng.randint(1, 6)):
                    new.append(f"{indent}metrics.count(\"{rng.choice(NOUNS)}.{rng.choice(VERBS)}\", {k});")
            elif kind == "delete":
                i += rng.randint(1, 4)
            else:
                indent = old[i][: len(old[i]) - len(old[i].lstrip())]
                i += rng.randint(1, 3)
                new.append(f"{indent}// replaced by the agent: see {rng.choice(NOUNS)}.ts")
            next_change = i + rng.randint(30, 120)
            continue
        new.append(old[i])
        i += 1
    return new


def write_lines(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def gen_diff() -> dict:
    rng = random.Random(5000)
    old = code_lines(rng, 5000)
    new = scatter_changes(rng, old)
    write_lines(OUT / "diff" / "old.ts", old)
    write_lines(OUT / "diff" / "new.ts", new)
    return {"old": "diff/old.ts", "new": "diff/new.ts", "oldLines": len(old), "newLines": len(new)}


def gen_large() -> dict:
    rng = random.Random(5)
    lines: list[str] = []
    size = 0
    n = 0
    while size < 5 * MB:
        block = code_block(rng, n)
        n += 1
        lines += block
        size += sum(len(l) + 1 for l in block)
    write_lines(OUT / "large" / "large.ts", lines)
    path = OUT / "large" / "large.ts"
    return {"path": "large/large.ts", "bytes": path.stat().st_size, "lines": len(lines)}


# --- sample workspace ---------------------------------------------------------------------------

def git(cwd: Path, *args: str) -> None:
    env = {
        "GIT_AUTHOR_NAME": "Gako Bench", "GIT_AUTHOR_EMAIL": "bench@gako.app",
        "GIT_COMMITTER_NAME": "Gako Bench", "GIT_COMMITTER_EMAIL": "bench@gako.app",
        "GIT_AUTHOR_DATE": "2026-10-01T12:00:00Z", "GIT_COMMITTER_DATE": "2026-10-01T12:00:00Z",
        "GIT_CONFIG_NOSYSTEM": "1", "GIT_CONFIG_GLOBAL": str(Path(__file__).with_name("empty.gitconfig")),
    }
    subprocess.run(["git", "-c", "init.defaultBranch=main", "-c", "commit.gpgsign=false",
                    "-c", "core.autocrlf=false", *args],
                   cwd=cwd, check=True, capture_output=True, env={**os.environ, **env})


def gen_workspace() -> dict:
    base = OUT / "workspace" / "platform"
    if base.exists():
        shutil.rmtree(base)
    base.mkdir(parents=True)
    services = ["auth", "billing", "catalog", "gateway", "notify"]
    (base / "README.md").write_text("# platform\n\nBase repository. Services are independent repos under services/.\n")
    (base / ".gitignore").write_text("".join(f"/services/{s}/\n" for s in services))
    write_lines(base / "deploy" / "compose.yaml", ["services:"] + [f"  {s}:\n    build: ./services/{s}" for s in services])
    git(base, "init", "-q")
    git(base, "add", "-A")
    git(base, "commit", "-q", "-m", "Initial layout")
    # An uncommitted change in the base repo too.
    with (base / "README.md").open("a") as f:
        f.write("\nRun `make up` to start everything.\n")

    old = (OUT / "diff" / "old.ts").read_text()
    new = (OUT / "diff" / "new.ts").read_text()
    for k, name in enumerate(services):
        repo = base / "services" / name
        rng = random.Random(100 + k)
        (repo / "src").mkdir(parents=True)
        (repo / "README.md").write_text(f"# {name}\n\nThe {name} service.\n")
        for f in range(4):
            write_lines(repo / "src" / f"{rng.choice(NOUNS)}{f}.ts", code_lines(rng, rng.randint(80, 400)))
        if name == "catalog":
            (repo / "src" / "inventory.ts").write_text(old, newline="\n")
        git(repo, "init", "-q")
        git(repo, "add", "-A")
        git(repo, "commit", "-q", "-m", f"Initial {name} service")
        files = sorted(p for p in (repo / "src").glob("*.ts") if p.name != "inventory.ts")
        # Unstaged change, staged change, untracked file.
        with files[0].open("a") as fh:
            fh.write(f"export const {name}Version = \"0.{k + 1}.0\";\n")
        with files[1].open("a") as fh:
            fh.write("// staged change\n")
        git(repo, "add", str(files[1].relative_to(repo)))
        (repo / "src" / "scratch.ts").write_text(f"// untracked file in {name}\n")
        if name == "catalog":
            (repo / "src" / "inventory.ts").write_text(new, newline="\n")
    return {"base": "workspace/platform", "repos": [f"services/{s}" for s in services],
            "diffFile": "workspace/platform/services/catalog/src/inventory.ts"}


# --- dumps --------------------------------------------------------------------------------------

LEVELS = [("INFO ", "32"), ("DEBUG", "36"), ("WARN ", "33"), ("ERROR", "31")]
MESSAGES = ["request handled", "cache miss", "retrying upstream call", "connection pool resized",
            "slow query", "job finished", "token refreshed", "rebalancing partitions",
            "health check ok", "payload validated", "queue depth high", "lock acquired"]


def write_log(path: Path, size: int, seed: int) -> dict:
    """Lines: `<seq> <time> <LEVEL> <service> <message> k=v ... #<crc32 of the text before ' #'>`."""
    rng = random.Random(seed)
    seq = 0
    written = 0
    with path.open("wb", buffering=4 * MB) as f:
        while written < size:
            seq += 1
            level, color = rng.choice(LEVELS)
            ms = seq * 7
            ts = f"2026-10-06T{(ms // 3600000) % 24:02d}:{(ms // 60000) % 60:02d}:{(ms // 1000) % 60:02d}.{ms % 1000:03d}Z"
            kv = " ".join(f"{rng.choice(NOUNS)}={rng.randint(0, 99999)}" for _ in range(rng.randint(1, 8)))
            plain_head = f"{seq:09} {ts} "
            plain_tail = f" {rng.choice(NOUNS)}-svc {rng.choice(MESSAGES)} {kv}"
            plain = plain_head + level + plain_tail
            crc = zlib.crc32(plain.encode())
            line = f"{plain_head}\x1b[{color}m{level}\x1b[0m{plain_tail} \x1b[2m#{crc:08x}\x1b[0m\n".encode()
            f.write(line)
            written += len(line)
        trailer = f"END-OF-DUMP {path.name} lines={seq}\n".encode()
        f.write(trailer)
    return {"path": f"dumps/{path.name}", "bytes": path.stat().st_size, "kind": "log", "lastSeq": seq,
            "trailer": trailer.decode().strip()}


def write_long(path: Path, size: int, seed: int) -> dict:
    """A few dozen lines of 512 KB to 8 MB each."""
    rng = random.Random(seed)
    words = [rng.choice(NOUNS + VERBS) for _ in range(200_000)]
    block = " ".join(words).encode()
    written = 0
    lines = 0
    last = b""
    with path.open("wb", buffering=4 * MB) as f:
        while written < size:
            length = min(rng.randint(MB // 2, 8 * MB), max(size - written, 1024))
            start = rng.randint(0, len(block) - 1)
            parts = []
            remaining = length
            pos = start
            while remaining > 0:
                piece = block[pos:pos + remaining]
                parts.append(piece)
                remaining -= len(piece)
                pos = 0
            lines += 1
            line = f"[line {lines}] ".encode() + b"".join(parts)
            f.write(line + b"\n")
            written += len(line) + 1
            last = line
        trailer = f"END-OF-DUMP {path.name} lines={lines}\n".encode()
        f.write(trailer)
    return {"path": f"dumps/{path.name}", "bytes": path.stat().st_size, "kind": "long", "lines": lines,
            "tail": last[-2000:].decode(), "trailer": trailer.decode().strip()}


def write_emoji(path: Path, size: int, seed: int) -> dict:
    """Long runs of combining marks on one base character, mixed with emoji sequences."""
    rng = random.Random(seed)
    zwj = ["\U0001F468‍\U0001F469‍\U0001F467‍\U0001F466",  # family
           "\U0001F469‍\U0001F4BB",  # woman technologist
           "\U0001F3F3️‍\U0001F308",  # rainbow flag
           "\U0001F9D1‍\U0001F91D‍\U0001F9D1"]  # people holding hands
    flags = ["\U0001F1EF\U0001F1F5", "\U0001F1E7\U0001F1F7", "\U0001F1FA\U0001F1F8", "\U0001F1E9\U0001F1EA",
             "\U0001F1F5\U0001F1F9"]
    skin = [f"\U0001F44D{chr(0x1F3FB + i)}" for i in range(5)] + [f"\U0001F44B{chr(0x1F3FB + i)}" for i in range(5)]

    def unit() -> str:
        r = rng.random()
        if r < 0.35:
            base = rng.choice("aeiouxyz")
            marks = "".join(chr(rng.randint(0x300, 0x36F)) for _ in range(rng.randint(8, 300)))
            return base + marks
        if r < 0.55:
            return rng.choice(zwj)
        if r < 0.7:
            return rng.choice(flags)
        if r < 0.85:
            return rng.choice(skin)
        return rng.choice(NOUNS)

    pool = [" ".join(unit() for _ in range(rng.randint(5, 80))).encode() for _ in range(3000)]
    written = 0
    seq = 0
    last = b""
    with path.open("wb", buffering=4 * MB) as f:
        while written < size:
            seq += 1
            line = f"{seq:09} ".encode() + rng.choice(pool)
            f.write(line + b"\n")
            written += len(line) + 1
            last = line
        trailer = f"END-OF-DUMP {path.name} lines={seq}\n".encode()
        f.write(trailer)
    return {"path": f"dumps/{path.name}", "bytes": path.stat().st_size, "kind": "emoji", "lastSeq": seq,
            "tail": last.decode(), "trailer": trailer.decode().strip()}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--force", action="store_true", help="regenerate everything")
    args = ap.parse_args()

    manifest_path = OUT / "manifest.json"
    if manifest_path.exists() and not args.force:
        manifest = json.loads(manifest_path.read_text())
        if manifest.get("version") == VERSION:
            print(f"fixtures are up to date in {OUT} (use --force to regenerate)")
            return
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "dumps").mkdir(parents=True)

    manifest: dict = {"version": VERSION}
    steps = [
        ("diff", gen_diff),
        ("large", gen_large),
        ("workspace", gen_workspace),
        ("normal", lambda: write_log(OUT / "dumps" / "normal.log", 250 * MB, 1)),
        ("long", lambda: write_long(OUT / "dumps" / "long.txt", 250 * MB, 2)),
        ("emoji", lambda: write_emoji(OUT / "dumps" / "emoji.txt", 250 * MB, 3)),
        ("load", lambda: write_log(OUT / "dumps" / "load.log", 50 * MB, 4)),
    ]
    for name, step in steps:
        t = time.perf_counter()
        manifest[name] = step()
        print(f"{name:10} {time.perf_counter() - t:6.1f} s", flush=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    sys.exit(main())
